#!/usr/bin/env php
<?php

declare(strict_types=1);

use Gacela\Framework\Gacela;
use Phel\Build\BuildFacade;
use Phel\Formatter\FormatterFacade;
use Phel\Interop\InteropFacade;
use Phel\Run\RunFacade;
use Symfony\Component\Console\Application;

$projectRootDir = getcwd() . DIRECTORY_SEPARATOR;
$autoloadPath = $projectRootDir . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';

if (!file_exists($autoloadPath)) {
    exit("Cannot load composer's autoload file: $autoloadPath\n");
}

require $autoloadPath;

Gacela::bootstrap($projectRootDir, [
    'config' => [
        'type' => 'php',
        'path' => 'phel-config.php',
        'path_local' => 'phel-config-local.php',
    ],
]);

$interopFacade = new InteropFacade();
$formatterFacade = new FormatterFacade();
$runFacade = new RunFacade();
$buildFacade = new BuildFacade();

$application = new Application();
$application->add($interopFacade->getExportCommand());
$application->add($formatterFacade->getFormatCommand());
$application->add($runFacade->getReplCommand());
$application->add($runFacade->getRunCommand());
$application->add($runFacade->getTestCommand());
$application->add($buildFacade->getCompileCommand());
$application->run();
