#!/usr/bin/env php
<?php

declare(strict_types=1);

use Gacela\Framework\Gacela;
use Phel\Console\Infrastructure\ConsoleBootstrap;
use Phel\Filesystem\FilesystemFacade;
use Phel\Phel;

$projectRootDir = getcwd() . DIRECTORY_SEPARATOR;
$autoloadPath = $projectRootDir . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';

if (!file_exists($autoloadPath)) {
    exit("Cannot load composer's autoload file: {$autoloadPath}\n");
}

require $autoloadPath;

Gacela::bootstrap($projectRootDir, Phel::configFn());

$bootstrap = new ConsoleBootstrap();
$bootstrap->run();
