<?php

declare(strict_types=1);

namespace PhelTest\Unit\Command\Runtime;

use Phel\Command\Runtime\RuntimeFileGenerator;
use PHPUnit\Framework\TestCase;

final class RuntimeFileGeneratorTest extends TestCase
{
    public function test_generate_template(): void
    {
        $config = [
            'my-namespace\\' => ['/src/'],
            'my-other-namespace\\' => ['/lib/', '/other/'],
            'my-test-namespace\\' => ['/tests/'],
        ];

        $fileGenerator = new RuntimeFileGenerator();
        $result = $fileGenerator->generate($config);

        $expected = <<<'EOF'
<?php

// @generated by Phel
use Phel\Runtime\RuntimeSingleton;

require __DIR__ .'/autoload.php';

$rt = RuntimeSingleton::initialize();
$rt->loadNs("phel\\core");
$rt->addPath("my-namespace\\", [__DIR__ . '/src/']);
$rt->addPath("my-other-namespace\\", [__DIR__ . '/lib/', __DIR__ . '/other/']);
$rt->addPath("my-test-namespace\\", [__DIR__ . '/tests/']);
return $rt;

EOF;
        self::assertEquals($expected, $result);
    }
}
