<?php

declare(strict_types=1);

namespace PhelTest\Support;

use Phel\Api\ApiConfig;
use Phel\Api\ApiFacade;
use Phel\Shared\Api\PhelFunction;

use function dirname;
use function implode;
use function sprintf;
use function strlen;

/**
 * Renders the public Phel-level API (every `phel.*` namespace the standard
 * library ships) as a stable, diffable text snapshot.
 *
 * This is the language half of what {@see PublicApiSurface} does for PHP. Promise
 * 1 in `docs/stability.md` is that Phel source compiling on 1.0.0 still compiles
 * on every later 1.x, and a function that quietly loses an arity or gains a
 * required parameter breaks that promise as surely as one that disappears.
 *
 * Only the name and the arities are captured. Docstrings, examples and source
 * locations move constantly and are not part of the contract.
 */
final readonly class CoreApiSurface
{
    public function __construct(
        private ApiFacade $apiFacade,
    ) {}

    public static function withApiFacade(): self
    {
        return new self(new ApiFacade());
    }

    public function render(): string
    {
        $lines = [
            '# Phel public standard-library API surface.',
            '#',
            '# Generated by `composer core-api:update`; documented in docs/stability.md',
            '# and docs/spec/language-surface.md.',
            '#',
            '# One line per public definition: `<ns>/<name>  <arities>`. A definition that',
            '# loses an arity or gains a required parameter breaks source compatibility just',
            '# as surely as one that disappears, so both are visible here.',
            '',
        ];

        foreach ($this->renderedDefinitions() as $line) {
            $lines[] = $line;
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * @return list<string>
     */
    public function renderedDefinitions(): array
    {
        $lines = [];

        foreach ($this->apiFacade->getPhelFunctions(ApiConfig::allNamespaces()) as $function) {
            $lines[] = $this->renderDefinition($function);
        }

        sort($lines);

        return $lines;
    }

    public static function snapshotPath(): string
    {
        return dirname(__DIR__, 3) . '/tests/php/Integration/Api/core-api.snapshot.txt';
    }

    private function renderDefinition(PhelFunction $function): string
    {
        // A `def` (as opposed to a `defn`) has no signature at all. Rendering the
        // empty case as `<value>` keeps a def-to-defn change visible in the diff.
        $signatures = $function->signatures === []
            ? '<value>'
            : implode(' | ', $function->signatures);

        return sprintf('phel.%s/%s  %s', $function->namespace, $this->bareName($function), $signatures);
    }

    /**
     * `PhelFunction::$name` is qualified for every namespace except `core`, where
     * it is bare. Qualifying all of them uniformly keeps the file sorted by
     * namespace and keeps a symbol moving between namespaces visible as a move.
     */
    private function bareName(PhelFunction $function): string
    {
        $prefix = $function->namespace . '/';

        return str_starts_with($function->name, $prefix)
            ? substr($function->name, strlen($prefix))
            : $function->name;
    }
}
