<?php

declare(strict_types=1);

namespace PhelTest\Support;

use BackedEnum;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use ReflectionClass;
use ReflectionClassConstant;
use ReflectionEnum;
use ReflectionMethod;
use ReflectionNamedType;
use ReflectionParameter;
use ReflectionProperty;
use ReflectionType;
use ReflectionUnionType;
use SplFileInfo;
use UnitEnum;

use function dirname;
use function implode;
use function in_array;
use function is_array;
use function is_object;
use function sprintf;
use function str_starts_with;

/**
 * Renders the public PHP API as a stable, diffable text snapshot.
 *
 * The rules encoded in {@see isPublicSymbol()} are the machine-readable half of
 * `docs/stability.md`. Everything they match is covered by semver from 1.0 on;
 * everything they reject is internal and free to change in a patch.
 *
 * Inherited members are attributed to whichever entry a consumer can actually
 * reach them through: a public parent gets its own entry, an internal Phel parent
 * is folded into its child, and a vendor parent is left alone so the snapshot does
 * not churn every time a dependency moves a base class.
 */
final readonly class PublicApiSurface
{
    /**
     * Whole namespaces whose every symbol is public.
     *
     * These are the namespaces a consumer cannot avoid: the values that cross a
     * facade boundary, the contracts those facades speak in, and the object a
     * project's own `phel-config.php` constructs.
     *
     * @var list<string>
     */
    private const array PUBLIC_NAMESPACES = [
        'Phel\\Config\\',
        'Phel\\Lang\\',
        'Phel\\Shared\\',
    ];

    /**
     * Emitted PHP calls straight into the global `Phel` class, so every compiled
     * `.phel` file ever produced is a consumer of it.
     *
     * Its `Phel\Phel` base is *not* public: it is annotated "@internal use \Phel
     * instead". The members it declares still reach a consumer through the child,
     * so {@see foldedAncestorsOf()} folds them into this entry rather than giving
     * the base one of its own.
     */
    private const string RUNTIME_CLASS = 'Phel';

    public function __construct(
        private string $repositoryRoot,
    ) {}

    public static function fromRepositoryRoot(string $repositoryRoot): self
    {
        return new self($repositoryRoot);
    }

    public function render(): string
    {
        $lines = [
            '# Phel public PHP API surface.',
            '#',
            '# Generated by `composer api-surface:update`; the rules live in',
            '# tests/php/Support/PublicApiSurface.php and are documented in docs/stability.md.',
            '# A diff here is a backward-compatibility review, not a formatting change.',
            '',
        ];

        foreach ($this->publicClassNames() as $className) {
            foreach ($this->renderClass(new ReflectionClass($className)) as $line) {
                $lines[] = $line;
            }

            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    /**
     * @return list<class-string>
     */
    public function publicClassNames(): array
    {
        $names = [];

        foreach ($this->declaredClassNames() as $className) {
            if (!$this->isPublicSymbol($className)) {
                continue;
            }

            if (!class_exists($className) && !interface_exists($className) && !enum_exists($className)) {
                continue;
            }

            $names[] = $className;
        }

        sort($names);

        return $names;
    }

    /**
     * A symbol is public if and only if it matches one of the six rules in
     * `docs/stability.md`. The order here mirrors the order there.
     */
    public function isPublicSymbol(string $className): bool
    {
        if ($className === self::RUNTIME_CLASS) {
            return true;
        }

        foreach (self::PUBLIC_NAMESPACES as $namespace) {
            if (str_starts_with($className, $namespace)) {
                return true;
            }
        }

        return $this->isModuleFacade($className);
    }

    public static function repositoryRoot(): string
    {
        return dirname(__DIR__, 3);
    }

    public static function snapshotPath(): string
    {
        return self::repositoryRoot() . '/tests/php/Unit/Architecture/public-api.snapshot.txt';
    }

    /**
     * `Phel\Compiler\CompilerFacade` and `Phel\Fiber\FiberFacadeInterface`, but
     * not `Phel\Run\Infrastructure\Command\SomethingFacade`: a facade is public
     * only when it sits directly under its module root and is named after it.
     */
    private function isModuleFacade(string $className): bool
    {
        if (preg_match('/^Phel\\\\(\w+)\\\\(\w+)(Facade|FacadeInterface)$/', $className, $matches) !== 1) {
            return false;
        }

        return $matches[1] === $matches[2];
    }

    /**
     * Every class-like symbol declared under `src/`, derived from the PSR-4 path
     * rather than from `get_declared_classes()`, so the result does not depend on
     * what the autoloader happened to touch first.
     *
     * @return list<class-string>
     */
    private function declaredClassNames(): array
    {
        $names = [self::RUNTIME_CLASS];
        $baseDir = $this->repositoryRoot . '/src/php';

        /** @var SplFileInfo $file */
        foreach (new RecursiveIteratorIterator(new RecursiveDirectoryIterator($baseDir)) as $file) {
            if (!$file->isFile()) {
                continue;
            }

            if ($file->getExtension() !== 'php') {
                continue;
            }

            $relative = str_replace([$baseDir . '/', '.php'], '', $file->getPathname());
            $names[] = 'Phel\\' . str_replace('/', '\\', $relative);
        }

        return $names;
    }

    /**
     * The class itself plus every ancestor whose members reach a consumer only
     * through it: a Phel ancestor that is not public in its own right.
     *
     * The walk stops at the first public ancestor, which has its own entry, and
     * at the first vendor ancestor, whose contract is that vendor's to keep. The
     * one case in the repository is `Phel extends Phel\Phel`.
     *
     * @return list<string> declaring-class names, in walk order
     */
    private function foldedAncestorsOf(ReflectionClass $class): array
    {
        $names = [$class->getName()];

        for ($parent = $class->getParentClass(); $parent !== false; $parent = $parent->getParentClass()) {
            $name = $parent->getName();

            if ($this->isPublicSymbol($name)) {
                break;
            }

            if ($name !== self::RUNTIME_CLASS && !str_starts_with($name, 'Phel\\')) {
                break;
            }

            $names[] = $name;
        }

        return $names;
    }

    /**
     * @return list<string>
     */
    private function renderClass(ReflectionClass $class): array
    {
        $lines = [$this->renderClassHeader($class)];

        foreach ($this->renderEnumCases($class) as $line) {
            $lines[] = $line;
        }

        foreach ($this->renderConstants($class) as $line) {
            $lines[] = $line;
        }

        foreach ($this->renderProperties($class) as $line) {
            $lines[] = $line;
        }

        foreach ($this->renderMethods($class) as $line) {
            $lines[] = $line;
        }

        return $lines;
    }

    private function renderClassHeader(ReflectionClass $class): string
    {
        $modifiers = [];

        if ($class->isFinal() && !$class->isEnum()) {
            $modifiers[] = 'final';
        }

        if ($class->isAbstract() && !$class->isInterface()) {
            $modifiers[] = 'abstract';
        }

        if ($class->isReadOnly()) {
            $modifiers[] = 'readonly';
        }

        $kind = match (true) {
            $class->isInterface() => 'interface',
            $class->isEnum() => 'enum',
            $class->isTrait() => 'trait',
            default => 'class',
        };

        $header = sprintf('%s%s %s', $modifiers === [] ? '' : implode(' ', $modifiers) . ' ', $kind, $class->getName());

        if ($class->isEnum()) {
            $backing = new ReflectionEnum($class->getName())->getBackingType();
            if ($backing instanceof ReflectionType) {
                $header .= ': ' . $this->renderType($backing);
            }
        }

        $parent = $class->getParentClass();
        if ($parent !== false) {
            $header .= ' extends ' . $parent->getName();
        }

        // `getInterfaceNames()` is transitive and unordered; both would make the
        // snapshot churn on unrelated edits, so it is narrowed and sorted.
        $interfaces = $this->directInterfaceNames($class);
        if ($interfaces !== []) {
            $header .= ' implements ' . implode(', ', $interfaces);
        }

        return $header;
    }

    /**
     * @return list<string>
     */
    private function directInterfaceNames(ReflectionClass $class): array
    {
        $parent = $class->getParentClass();
        $inherited = $parent === false ? [] : $parent->getInterfaceNames();

        $direct = [];

        foreach ($class->getInterfaceNames() as $interface) {
            if (in_array($interface, $inherited, true)) {
                continue;
            }

            if ($class->isEnum() && in_array($interface, [UnitEnum::class, BackedEnum::class], true)) {
                continue;
            }

            $direct[] = $interface;
        }

        // A transitively implemented interface is already implied by the one that
        // extends it, so listing it adds noise without adding a contract.
        $implied = [];
        foreach ($direct as $interface) {
            foreach (class_implements($interface) ?: [] as $parentInterface) {
                $implied[$parentInterface] = true;
            }
        }

        $names = array_values(array_filter($direct, static fn(string $i): bool => !isset($implied[$i])));
        sort($names);

        return $names;
    }

    /**
     * @return list<string>
     */
    private function renderEnumCases(ReflectionClass $class): array
    {
        if (!$class->isEnum()) {
            return [];
        }

        $lines = [];

        foreach (new ReflectionEnum($class->getName())->getCases() as $case) {
            $value = $case->getBackingValue();
            $lines[] = sprintf(
                '  case %s%s',
                $case->getName(),
                $value === null ? '' : ' = ' . var_export($value, true),
            );
        }

        sort($lines);

        return $lines;
    }

    /**
     * Constant *values* are part of the surface, not just their names: several
     * are the literal keys Gacela reads out of a project's `phel-config.php`, so
     * changing one silently changes what an existing config file means.
     *
     * @return list<string>
     */
    private function renderConstants(ReflectionClass $class): array
    {
        $declaredBy = $this->foldedAncestorsOf($class);
        $lines = [];

        foreach ($class->getReflectionConstants() as $constant) {
            if (!in_array($constant->getDeclaringClass()->getName(), $declaredBy, true)) {
                continue;
            }

            if (!$this->isVisibleMember($class, $constant)) {
                continue;
            }

            // Reflection reports every enum case as a class constant too;
            // renderEnumCases() already covers them, with their backing values.
            if ($constant->isEnumCase()) {
                continue;
            }

            $type = $constant->getType();

            $lines[] = sprintf(
                '  %s const %s%s = %s',
                $this->visibilityOf($constant),
                $type instanceof ReflectionType ? $this->renderType($type) . ' ' : '',
                $constant->getName(),
                $this->renderValue($constant->getValue()),
            );
        }

        sort($lines);

        return $lines;
    }

    /**
     * @return list<string>
     */
    private function renderProperties(ReflectionClass $class): array
    {
        $declaredBy = $this->foldedAncestorsOf($class);
        $lines = [];

        foreach ($class->getProperties() as $property) {
            if (!in_array($property->getDeclaringClass()->getName(), $declaredBy, true)) {
                continue;
            }

            if (!$this->isVisibleMember($class, $property)) {
                continue;
            }

            $type = $property->getType();

            $lines[] = sprintf(
                '  %s%s%s %s$%s',
                $this->visibilityOf($property),
                $property->isStatic() ? ' static' : '',
                $property->isReadOnly() ? ' readonly' : '',
                $type instanceof ReflectionType ? $this->renderType($type) . ' ' : '',
                $property->getName(),
            );
        }

        sort($lines);

        return $lines;
    }

    /**
     * @return list<string>
     */
    private function renderMethods(ReflectionClass $class): array
    {
        $declaredBy = $this->foldedAncestorsOf($class);
        $lines = [];

        foreach ($class->getMethods() as $method) {
            if (!in_array($method->getDeclaringClass()->getName(), $declaredBy, true)) {
                continue;
            }

            if (!$this->isVisibleMember($class, $method)) {
                continue;
            }

            $lines[] = $this->renderMethod($class, $method);
        }

        sort($lines);

        return $lines;
    }

    private function renderMethod(ReflectionClass $class, ReflectionMethod $method): string
    {
        $modifiers = [$this->visibilityOf($method)];

        if ($method->isStatic()) {
            $modifiers[] = 'static';
        }

        if ($method->isAbstract() && !$class->isInterface()) {
            $modifiers[] = 'abstract';
        }

        if ($method->isFinal()) {
            $modifiers[] = 'final';
        }

        $declaringClass = $method->getDeclaringClass()->getName();

        $parameters = array_map(
            fn(ReflectionParameter $parameter): string => $this->renderParameter($parameter, $declaringClass),
            $method->getParameters(),
        );

        $returnType = $method->getReturnType();

        return sprintf(
            '  %s function %s(%s)%s',
            implode(' ', $modifiers),
            $method->getName(),
            implode(', ', $parameters),
            $returnType instanceof ReflectionType ? ': ' . $this->renderType($returnType, $declaringClass) : '',
        );
    }

    private function renderParameter(ReflectionParameter $parameter, ?string $selfClass = null): string
    {
        $type = $parameter->getType();

        $rendered = sprintf(
            '%s%s%s$%s',
            $type instanceof ReflectionType ? $this->renderType($type, $selfClass) . ' ' : '',
            $parameter->isPassedByReference() ? '&' : '',
            $parameter->isVariadic() ? '...' : '',
            $parameter->getName(),
        );

        if ($parameter->isVariadic()) {
            return $rendered;
        }

        if (!$parameter->isDefaultValueAvailable()) {
            return $rendered;
        }

        // Dropping a default is as breaking as adding a required parameter, and
        // changing one changes behaviour for every call site that omits it.
        return $rendered . ' = ' . $this->renderValue($parameter->getDefaultValue());
    }

    /**
     * Protected members are part of the contract only where they can be reached:
     * a `final` class cannot be extended, so nothing outside it can ever see one.
     */
    private function isVisibleMember(
        ReflectionClass $class,
        ReflectionMethod|ReflectionProperty|ReflectionClassConstant $member,
    ): bool {
        if ($member->isPublic()) {
            return true;
        }

        if (!$member->isProtected()) {
            return false;
        }

        return !$class->isFinal();
    }

    private function visibilityOf(
        ReflectionMethod|ReflectionProperty|ReflectionClassConstant $member,
    ): string {
        return $member->isProtected() ? 'protected' : 'public';
    }

    /**
     * @param string|null $selfClass the declaring class, used to normalise `self`
     */
    private function renderType(ReflectionType $type, ?string $selfClass = null): string
    {
        if ($type instanceof ReflectionNamedType) {
            $name = $type->getName();

            // PHP 8.4 reports a `self` return type as the literal `self`; 8.5
            // resolves it to the declaring class. They describe the same
            // contract, so both are rendered as the resolved name and the
            // snapshot stops depending on which PHP the suite ran under.
            if ($name === 'self' && $selfClass !== null) {
                $name = $selfClass;
            }

            return $type->allowsNull() && $name !== 'mixed' && $name !== 'null'
                ? '?' . $name
                : $name;
        }

        if ($type instanceof ReflectionUnionType) {
            $names = array_map(
                fn(ReflectionType $inner): string => $this->renderType($inner, $selfClass),
                $type->getTypes(),
            );
            sort($names);

            return implode('|', $names);
        }

        // Intersection types keep their declared order: `A&B` and `B&A` are the
        // same type, but there is no ordering to normalise against for the rest.
        return (string) $type;
    }

    private function renderValue(mixed $value): string
    {
        if ($value instanceof UnitEnum) {
            return $value::class . '::' . $value->name;
        }

        if (is_object($value)) {
            return 'object(' . $value::class . ')';
        }

        if ($value === null) {
            return 'null';
        }

        if (is_array($value)) {
            return $this->renderArray($value);
        }

        return var_export($value, true);
    }

    /**
     * `var_export()` renders an array across several lines with PHP 5 syntax.
     * Neither survives being embedded in a one-line signature, so arrays get a
     * compact rendering of their own.
     *
     * @param array<array-key, mixed> $value
     */
    private function renderArray(array $value): string
    {
        if ($value === []) {
            return '[]';
        }

        $isList = array_is_list($value);
        $parts = [];

        foreach ($value as $key => $item) {
            $parts[] = $isList
                ? $this->renderValue($item)
                : var_export($key, true) . ' => ' . $this->renderValue($item);
        }

        return '[' . implode(', ', $parts) . ']';
    }
}
