<?php

declare(strict_types=1);

namespace Phel\Run;

use Gacela\Framework\AbstractFacade;
use Gacela\Framework\Health\ModuleHealthCheckInterface;
use Phel\Run\Application\Test\Coverage\CoverageDriver;
use Phel\Run\Application\Test\Coverage\CoverageReport;
use Phel\Run\Application\Test\CpuCountDetector;
use Phel\Run\Application\Test\ParallelTestOrchestrator;
use Phel\Shared\CompileOptions;
use Phel\Shared\Eval\EvalResult;
use Phel\Shared\Exceptions\CompilerException;
use Phel\Shared\Facade\RunFacadeInterface;
use Phel\Shared\NamespaceInformation;
use Symfony\Component\Console\Output\OutputInterface;
use Throwable;

/**
 * @extends AbstractFacade<RunFactory>
 */
final class RunFacade extends AbstractFacade implements RunFacadeInterface
{
    public function runNamespace(string $namespace): void
    {
        $this->getFactory()
            ->createNamespaceRunner()
            ->run($namespace);
    }

    public function runFile(string $filename): void
    {
        $this->getFactory()
            ->createFileRunner()
            ->run($filename);
    }

    public function getNamespaceFromFile(string $fileOrPath): NamespaceInformation
    {
        return $this->getFactory()
            ->getBuildFacade()
            ->getNamespaceFromFile($fileOrPath);
    }

    public function getDependenciesFromPaths(array $paths): array
    {
        return $this->getFactory()
            ->createNamespaceCollector()
            ->getDependenciesFromPaths($paths);
    }

    public function getDependenciesForNamespace(array $directories, array $ns): array
    {
        return $this->getFactory()
            ->getBuildFacade()
            ->getDependenciesForNamespace($directories, $ns);
    }

    public function evalFile(NamespaceInformation $info): void
    {
        $this->getFactory()
            ->getBuildFacade()
            ->evalFile($info->getFile());
    }

    public function eval(string $phelCode, CompileOptions $compileOptions = new CompileOptions()): mixed
    {
        return $this->getFactory()
            ->getCompilerFacade()
            ->eval($phelCode, $compileOptions);
    }

    public function enableDebugLineTap(?string $phelFileFilter = null, string $logPath = './phel-debug.log'): void
    {
        $this->getFactory()
            ->getCompilerFacade()
            ->enableDebugLineTap($phelFileFilter, $logPath);
    }

    public function disableDebugLineTap(): void
    {
        $this->getFactory()
            ->getCompilerFacade()
            ->disableDebugLineTap();
    }

    public function structuredEval(string $phelCode, CompileOptions $compileOptions = new CompileOptions()): EvalResult
    {
        return $this->getFactory()
            ->createStructuredEvaluator()
            ->eval($phelCode, $compileOptions);
    }

    public function writeLocatedException(OutputInterface $output, CompilerException $e): void
    {
        $this->getFactory()
            ->getCommandFacade()
            ->writeLocatedException(
                $output,
                $e->getNestedException(),
                $e->getCodeSnippet(),
            );
    }

    public function writeStackTrace(OutputInterface $output, Throwable $e): void
    {
        $this->getFactory()
            ->getCommandFacade()
            ->writeStackTrace($output, $e);
    }

    public function getAllPhelDirectories(): array
    {
        return $this->getFactory()
            ->getCommandFacade()
            ->getAllPhelDirectories();
    }

    /**
     * @return list<NamespaceInformation>
     */
    public function getLoadedNamespaces(): array
    {
        return $this->getFactory()
            ->createNamespacesLoader()
            ->getLoadedNamespaces();
    }

    public function getVersion(): string
    {
        return $this->getFactory()
            ->createVersionResolver()
            ->resolve();
    }

    public function loadPhelNamespaces(?string $replStartupFile = null): void
    {
        $this->getFactory()
            ->createNamespaceLoader()
            ->loadPhelNamespaces($replStartupFile);
    }

    /**
     * Auto-detect the main entry point file from conventional locations.
     * Prefers main.phel (the default generated by `phel init`), falls back
     * to core.phel for older projects.
     *
     * @return string|null File path if found, null otherwise
     */
    public function autoDetectEntryPoint(): ?string
    {
        return $this->getFactory()
            ->createEntryPointDetector()
            ->detect();
    }

    public function createParallelTestOrchestrator(): ParallelTestOrchestrator
    {
        return $this->getFactory()->createParallelTestOrchestrator();
    }

    public function createCpuCountDetector(): CpuCountDetector
    {
        return $this->getFactory()->createCpuCountDetector();
    }

    /**
     * Runs `$runTests` once, then again on every change under the project's
     * source and test directories. Blocks until terminated; returns the exit
     * code of the most recent run.
     *
     * @param callable():int $runTests
     */
    public function runTestWatchLoop(callable $runTests, OutputInterface $output): int
    {
        return $this->getFactory()
            ->createTestWatchRunner()
            ->run($runTests, $output);
    }

    /**
     * @return list<ModuleHealthCheckInterface>
     */
    public function getModuleHealthChecks(): array
    {
        return $this->getFactory()->getModuleHealthChecks();
    }

    /**
     * Detect the loaded line-coverage driver (pcov preferred, else xdebug), or
     * null when neither extension is available.
     */
    public function detectCoverageDriver(): ?CoverageDriver
    {
        return $this->getFactory()->createCoverageDriver();
    }

    /**
     * Build a per-`.phel`-file coverage report from raw PHP line coverage.
     *
     * @param array<string, array<int, int>> $rawCoverage
     */
    public function buildCoverageReport(array $rawCoverage, string $driverName): CoverageReport
    {
        return $this->getFactory()
            ->createCoverageAggregator($driverName)
            ->aggregate($rawCoverage);
    }
}
