<?php

declare(strict_types=1);

namespace Phel\Lang;

use ReflectionClass;
use Stringable;

use function is_string;

/**
 * Subclasses generated by the compiler always implement `__invoke` with a
 * concrete (positional, possibly typed) signature. Declaring it via PHPDoc
 * keeps static analysers happy without forcing LSP onto every callable's
 * generated signature.
 *
 * @method mixed __invoke(mixed ...$args)
 */
abstract class AbstractFn implements FnInterface, MetaInterface, Stringable
{
    use MetaTrait;

    public function __toString(): string
    {
        $boundTo = new ReflectionClass($this)->getConstant('BOUND_TO');

        if (!is_string($boundTo) || $boundTo === '') {
            return '<function>';
        }

        $lastSeparator = strrpos($boundTo, '\\');
        $encodedName = $lastSeparator !== false
            ? substr($boundTo, $lastSeparator + 1)
            : $boundTo;

        return '<function:' . str_replace('_', '-', $encodedName) . '>';
    }

    /**
     * Non-magic invocation path used by emitted call sites that have proven
     * the callee is an `AbstractFn`. Direct method call to `__invoke` skips
     * PHP's magic-method lookup (~2x the cost of a regular call), which is
     * the hot path of generated Phel code.
     */
    public function call(mixed ...$args): mixed
    {
        /** @psalm-suppress UndefinedMethod */
        return $this->__invoke(...$args);
    }

}
