<?php

declare(strict_types=1);

namespace Phel\Command\Runtime;

final class RuntimeFileGenerator
{
    /**
     * @param array<string, list<string>> $config [ns => [path1, path2, ...]]
     */
    public function generate(array $config): string
    {
        $template = <<<'EOF'
<?php

// @generated by Phel
use Phel\Runtime\RuntimeSingleton;

require __DIR__ .'/autoload.php';

$rt = RuntimeSingleton::initialize();

EOF;

        foreach ($config as $ns => $paths) {
            $encodedNs = addslashes($ns);
            $pathString = implode("', __DIR__ . '", array_map('addslashes', $paths));
            $template .= "\$rt->addPath(\"$encodedNs\", [__DIR__ . '$pathString']);\n";
        }

        $template .= "return \$rt;\n";

        return $template;
    }
}
