# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: Quality

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: quality-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  composer-validate:
    name: Validate composer configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none
          tools: composer

      - name: Validate composer configuration
        run: composer validate --strict --quiet --no-interaction --no-check-all --no-check-lock

  coding-guidelines:
    name: Coding Guidelines
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-phel

      - name: Run friendsofphp/php-cs-fixer
        run: ./vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run --show-progress=dots --using-cache=no --verbose

      - name: Run rector/rector
        run: ./vendor/bin/rector process --dry-run --config=rector.php

  type-checker:
    name: Type Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-phel

      - name: Run Psalm on internal code
        run: ./vendor/bin/psalm --config=psalm.xml --no-progress --shepherd --show-info=false --stats --php-version=8.4

      - name: Run PHPStan (level 9) on internal code
        run: ./vendor/bin/phpstan --memory-limit=516M --debug -vvv
